version: '3'

services:
  mongo:
    image: 'mongo'
    ports:
    - "27017:27017"
  web:
    image: eshadatta/crmds_demo
    command: bundle exec unicorn -p 3000 -d -c unicorn.rb
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - CROSSREF_API_TOKEN=${CROSSREF_API_TOKEN}
