version: '3'

networks:
  crossref:
    # 'external' means specified outside this file, not an external network
    external:
      name: crossref

services:
  web:
    #image: eshadatta/test-crmds:dev
    image: eshadatta/test-crmds:external
    #build: .
    command: bundle exec unicorn -p 3000 -d -c unicorn.rb 
    networks: 
      - crossref
    ports:
      - "3000:3000"
