source "http://rubygems.org"
gem 'sinatra'
gem 'haml'
gem 'mongo'
gem 'json'
gem 'bson_ext'
gem 'rsolr'
gem 'will_paginate'
gem 'bson'
gem 'faraday'
gem 'faraday_middleware'
gem 'gabba'
gem 'omniauth-orcid'
gem 'rack-session-mongo'
gem 'oauth2'
gem 'resque'
gem 'resque-pool'
gem 'nokogiri'
gem 'rake'
gem 'parallel'
gem 'unicorn'
gem 'pry'

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'capybara-screenshot'
  gem 'factory_girl'
  gem 'poltergeist'
  gem 'webmock'
  gem 'vcr'
end
