source "http://rubygems.org"
gem 'sinatra'
gem 'haml'
gem 'mongo', '~> 1.12', '>= 1.12.5'
gem "rack", ">= 1.6.11"
gem 'json'
gem 'bson_ext'
gem 'rsolr'
gem 'will_paginate'
gem 'bson'
gem 'faraday'
gem 'faraday_middleware'
gem 'gabba'
gem 'omniauth-orcid'
gem 'rack-session-mongo'
gem 'oauth2'
gem 'resque'
gem 'resque-pool'
gem 'nokogiri'
gem 'rake'
gem 'parallel'
gem 'unicorn'
gem 'pry'
